name: Daily Build
on:
  schedule:
    - cron: "0 2 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.GATSBY_BUILD_WEBHOOK_URL }}
          data: "N/A"
      - name: Log success
        run: echo success
